# Jekyll Resume Theme

# Site settings
title: Visuology
email: jeroen.laven@me.com
description: Putting logic back in vision.
baseurl: "https://visuology.github.io/visuology/"
url: "https://visuology.nl"
name: Jeroen Lavèn
job: digital communicator
location: Rotterdam, NL
languages: new media, contemporary art, and exhibition design
twitter_username: visuology_nl
linkedin_username:  visuology
instagram_username: visuology_nl
email_address: jeroen.laven@me.com

# Build settings
markdown: kramdown
