# Jekyll Resume Theme

# Site settings
title: Visuology
email: jeroen.laven@me.com
description: Putting logic back in vision.
baseurl: "https://visuology.github.io/visuology/"
url: "http://visuology.nl"
name: Jeroen Lavèn
job: digital communications native
location: Rotterdam, NL
languages: New Media, Contemporary Art and Exhibition Design
twitter_username: visuology_nl
linkedin_username:  visuology
instagram_username: visuology_nl
email_address: jeroen.laven@me.com

# Build settings
markdown: kramdown
