# Jekyll Resume Theme

# Site settings
title: Visuology
email: jeroen.laven@me.com
description: Putting logic back in vision.
baseurl: "https://visuology.github.io/visuology/"
url: "http://visuology.nl"
name: Jeroen Lavèn
job: PR & Social Media Editor
location: Rotterdam, NL
languages: Contemporary Art, Exhibition Design and New Media
twitter_username: visuology_nl
github_username:  visuology
intagram_username: visuology_nl
email_address: jeroen.laven@me.com

# Build settings
markdown: kramdown
