# Jekyll Resume Theme

# Site settings
title: Visuology
email: jeroen.laven@me.com
description: Putting logic back in vision.
baseurl: "http://visuology.nl"
url: "http://visuology.nl"
name: Jeroen Laven
job: PR & Social Media Editor
location: Birmingham, UK
languages: HTML, CSS and Javascript
twitter_username: visuology_nl
github_username:  visuology
intagram_username: visuology_nl
email_address: jeroen.laven@me.com

# Build settings
markdown: kramdown
